# Conda environment specification. The dependencies defined in this file will
# be automatically provisioned for managed runs. These include runs against
# the localdocker, remotedocker, and cluster compute targets.

# Note that this file is NOT used to automatically manage dependencies for the
# local compute target. To provision these dependencies locally, run:
# conda env update --file conda_dependencies.yml

# Details about the Conda environment file format:
# https://conda.io/docs/using/envs.html#create-environment-file-by-hand

# For managing Spark packages and configuration, see spark_dependencies.yml.

name: project_environment
dependencies:
  # The python interpreter version.
  # Currently Azure ML Workbench only supports 3.5.2.
  - python=3.5.2
  - ipywidgets==5.2.2
  - seaborn
  - statsmodels
  - scikit-learn
  - requests
  - pandas
  - matplotlib

  # Required for Jupyter Notebooks.
  - ipykernel=4.6.1
  
  - pip:

    # The API for Azure Machine Learning Model Management Service.
    - azure-ml-api-sdk==0.1.0a11
  
    # Library for collecting data from operationalized models
    - azureml-model-management-sdk==1.0.1b6